name: dage
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.1.1
  - certifi=2019.11.28
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1e
  - pip=20.0.2
  - python=3.7.6
  - readline=7.0
  - setuptools=46.1.1
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.9.0
    - astor==0.8.1
    - astroid==2.3.3
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.3
    - chardet==3.0.4
    - cycler==0.10.0
    - datasetops==0.0.6
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - entrypoints==0.3
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.2.0
    - googleapis-common-protos==1.51.0
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.9
    - importlib-metadata==1.5.0
    - ipykernel==5.1.2
    - ipython==7.8.0
    - ipython-genutils==0.2.0
    - isort==4.3.21
    - jedi==0.16.0
    - jinja2==2.11.1
    - joblib==0.14.0
    - json5==0.9.3
    - jsonschema==3.2.0
    - jupyter-client==5.3.3
    - jupyter-core==4.5.0
    - jupyterlab==1.1.4
    - jupyterlab-server==1.0.6
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - lazy-object-proxy==1.4.3
    - markdown==3.2.1
    - markupsafe==1.1.1
    - matplotlib==3.1.1
    - mccabe==0.6.1
    - mistune==0.8.4
    - nbconvert==5.6.0
    - nbformat==4.4.0
    - notebook==6.0.1
    - numpy==1.17.2
    - opt-einsum==3.2.0
    - pandas==0.25.1
    - pandocfilters==1.4.2
    - parso==0.6.2
    - pathlib==1.0.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - prometheus-client==0.7.1
    - promise==2.3
    - prompt-toolkit==2.0.10
    - protobuf==3.11.3
    - ptyprocess==0.6.0
    - pyaml==20.3.1
    - pygments==2.6.1
    - pylint==2.4.2
    - pyparsing==2.4.2
    - pyrsistent==0.15.4
    - python-dateutil==2.8.0
    - python-dotenv==0.10.3
    - python-pushover==0.4
    - pytz==2019.3
    - pyyaml==5.3.1
    - pyzmq==19.0.0
    - requests==2.23.0
    - scikit-learn==0.21.3
    - scikit-optimize==0.5.2+41.ge082d80
    - scipy==1.3.1
    - seaborn==0.9.0
    - send2trash==1.5.0
    - six==1.14.0
    - tensorboard==1.15.0
    - tensorflow-datasets==2.1.0
    - tensorflow-estimator==1.15.1
    - tensorflow-gpu==1.15.2
    - tensorflow-metadata==0.21.1
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - torch==1.4.0
    - torchvision==0.5.0
    - tornado==6.0.4
    - tqdm==4.36.1
    - traitlets==4.3.3
    - typed-ast==1.4.1
    - urllib3==1.25.7
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - werkzeug==1.0.0
    - wrapt==1.12.1
    - zipp==3.1.0

